receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]
  hostmetrics:
    collection_interval: 10s
    scrapers:
      load:
      cpu:
      disk:

  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  file:
    path: ./file_metrics_data.json
  file/2:
    path: ./file_trace_data.json
  datadog:
    api:
      key: "<KEY>"
  otlp:
    endpoint: "otel-collector.default:4317"
    insecure: true
    sending_queue:
      num_consumers: 4
      queue_size: 100
    retry_on_failure:
       enabled: true
      
service:
  pipelines:
    metrics:
      #receivers: [hostmetrics]
      receivers: [prometheus]
      processors: [batch]
      exporters: [file]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/2]
      #exporters: [datadog]
      #exporters: [otlp]
